catchpick/catchpick/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsCatch.urls', )),
]

catchpick/newsCatch/urls.py
from django.urls import path
from . import views
app_name='newsCatch'
urlpatterns = [
    path('', views.index , name='index'),
    path('politics/', views.politics , name='politics'),
    path('culture/', views.culture , name='culture'),
    path('society/', views.society , name='society'),
    path('economy/', views.economy , name='economy'),
    path('international/', views.international , name='international'),
    path('sports/', views.sports , name='sports'),
    path('etc/', views.etc , name='etc'),
    path('about/', views.about, name='about'),
    path('subscription/', views.subscription, name='subscription'),
    path('unsubscription/', views.unsubscription, name='unsubscription'),
    path('errorsubs/', views.errorsubs, name='errorsubs'),
    path('errorunsubs/', views.errorunsubs, name='errorunsubs'),
]

catchpick/newsCatch/models.py
from django.db import models


# Create your models here.
class TitleData(models.Model):
    title = models.CharField(max_length=100)
    time = models.CharField(max_length=100, default=0)
    nowRank = models.CharField(max_length=100, default=21)

    def __str__(self):
        return self.title

class AccumulateData(models.Model):
    title = models.CharField(max_length=100)
    time = models.CharField(max_length=100, default=0)
    maxRank = models.CharField(max_length=100, default=21)
    toNewsTest = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class NewsTestData(models.Model):
    title = models.CharField(max_length=100)
    time = models.CharField(max_length=100, default=0)
    maxRank = models.CharField(max_length=100, default=21)

    def __str__(self):
        return self.title

class VerifiedData(models.Model):
    title = models.CharField(max_length=100)
    time = models.CharField(max_length=100, default=0)
    maxRank = models.CharField(max_length=100, default=21)
    category = models.CharField(max_length=100)
    news_KH_title = models.CharField(max_length=500)
    news_KH_link = models.CharField(max_length=500)
    news_HKR_title = models.CharField(max_length=500)
    news_HKR_link = models.CharField(max_length=500)
    news_CS_title = models.CharField(max_length=500)
    news_CS_link = models.CharField(max_length=500)
    news_CA_title = models.CharField(max_length=500)
    news_CA_link = models.CharField(max_length=500)
    news_KBS_title = models.CharField(max_length=500)
    news_KBS_link = models.CharField(max_length=500)
    news_MBC_title = models.CharField(max_length=500)
    news_MBC_link = models.CharField(max_length=500)
    news_SBS_title = models.CharField(max_length=500)
    news_SBS_link = models.CharField(max_length=500)
    news_YTN_title = models.CharField(max_length=500)
    news_YTN_link = models.CharField(max_length=500)

    def __str__(self):
        return self.title

class EmailData(models.Model):
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.email

catchpick/newsCatch/forms.py
from django.forms import ModelForm
from django import forms
from .models import EmailData

class EmailForm(forms.ModelForm):
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={'class': 'input100', 'name': 'email'}
        )
    )

    class Meta:
        model = EmailData
        fields = ('email',)

catchpick/newsCatch/views.py
from django.shortcuts import render, redirect
from .forms import EmailForm
from .models import EmailData, VerifiedData
from django.core.exceptions import ObjectDoesNotExist
import time
# Create your views here.

def index(request):
    return redirect('newsCatch:politics')

def politics(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="정치").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/politics.html', {'all_news_data': all_news_data, 'news_data': news_data})
def culture(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="문화").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/culture.html', {'all_news_data': all_news_data, 'news_data': news_data})
def society(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="사회").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/society.html', {'all_news_data': all_news_data, 'news_data': news_data})
def economy(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="경제").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/economy.html', {'all_news_data': all_news_data, 'news_data': news_data})
def international(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="국제").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/international.html', {'all_news_data': all_news_data, 'news_data': news_data})
def sports(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="스포츠").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/sports.html', {'all_news_data': all_news_data, 'news_data': news_data})
def etc(request):
    all_news_data = list(reversed(VerifiedData.objects.all().order_by('time')))
    if len(all_news_data) != 0:
        for j in all_news_data:
            j.title = j.title + ', '
        all_news_data[len(all_news_data) - 1].title = all_news_data[len(all_news_data) - 1].title[:-2]
    news_data = list(reversed(VerifiedData.objects.filter(category="기타").order_by('time')))
    for i in news_data:
        i.time = time.strftime('%m월 %d일 %H:%M ~', time.localtime(float(i.time)))
    return render(request, 'newsCatch/etc.html', {'all_news_data': all_news_data, 'news_data': news_data})

def about(request):
    return render(request,'newsCatch/about.html')

def subscription(request): # 구독 페이지 처리
    if request.method == "POST":
        form = EmailForm(request.POST)

        if form.is_valid(): #폼이 유효하면 이메일 저장
            if EmailData.objects.filter(email=request.POST.get('email')).count() == 0: #EmailData DB에 입력된 이메일이 없다면 이메일 저장
                subscription = form.save()
                return redirect('newsCatch:politics')
            else:  #EmailData DB에 이미 있는 이메일이면 에러페이지로 이동
                return redirect('newsCatch:errorsubs')
        else: #이메일 형석 예외처리
            return redirect('newsCatch:errorsubs')
    else:
        form = EmailForm()
        return render(request, 'newsCatch/subscription.html', {'form': form})
def unsubscription(request): #구독취소 페이지 처리
    if request.method == "POST":

        form = EmailForm(request.POST)
        del_email = request.POST.get('email')
        try: #삭제하려는 이메일이 EmailData DB에 있으면 삭제
            if form.is_valid() and EmailData.objects.get(email=del_email):
                unsubscription = EmailData.objects.get(email=del_email)
                unsubscription.delete()
                return redirect('newsCatch:politics')
            else: #이메일 형식 예외처리
                return redirect('newsCatch:errorunsubs')
        except ObjectDoesNotExist: #삭제하려는 이메일이 EmailData DB에 없다면 에러페이지 출력
            return redirect('newsCatch:errorunsubs')
    else:
        form = EmailForm()
        return render(request, 'newsCatch/unsubscription.html', {'form': form})

def errorsubs(request):
    return render(request, 'newsCatch/sub_emailError.html')

def errorunsubs(request):
    return render(request, 'newsCatch/unsub_emailError.html')

catchpick/newsCatch/templates/newsCatch/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>서비스소개</title>

    <link rel="icon" type="image/png" href="{% static 'fav.ico'%}"/>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css'%}" rel="stylesheet">
    <link href="{% static 'css/overlap.css'%}" rel="stylesheet">

    <style>
      img{
        display: block;
        margin : 0px auto;
        margin-top : 45px;
        position : relative;
        //-webkit-filer: opacity(.5) drop-shadow(#789038);
        //filter : opacity(.5) drop-shadow(#789038);
      }

      .button > a{
        display : block;
        margin : auto;
        margin-bottom : 30px;
        position : relative;
        float : right;
      }

      .introduce{
        color : black;
        border-bottom : 2px solid black;
        margin-bottom : 35px;
      }

      .standard{
        color : black;
        border-bottom : 2px solid black;
        margin-bottom : 35px;
      }

      .private_policy{
        color : black;
      }

      .private_policy > p{
        border-bottom : 1px solid gray;
        margin-bottom : 30px;
      }
  </style>
</head>

<body class="bg-gradient-primary about_back">


  <div class="container">

    <!-- Outer Row -->
      <div class="row justify-content-center">
        <div class = "header">
          <img src = "{% static 'img/logo.png'%}" width="300px">
        </div>
      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5 about">
                  <div class="button">
                    <div class="my-2"></div>
                    <a href="{% url 'newsCatch:politics' %}" class="btn btn-success btn-icon-split">
                      <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                      </span>
                      <span class="text">돌아가기</span>
                    </a>
                  </div><br><br><br>
                  <div class = "introduce">
                    <p class="lh6 bs4"><h3>서비스소개</h3></br> CatchPick(‘CatchPick’이하 ‘CatchPick') 은(는) 네이버 실시간 급상승 검색어에서 시사이슈만을 골라내 관련 뉴스를 카테고리별로 나눠서 보여주고 뉴스레터로 제공해주는 서비스입니다.</br></br></p>
                  </div>
                  <div class ="standard">
                    <p class="lh6 bs4"><h3>선정기준</h3></br> CatchPick(‘CatchPick’이하 ‘CatchPick') 은(는) 실시간 급상승 검색어가 3시간 이상 존재 시 8개의 뉴스 사이트(경향, 한겨레, 조선, 중앙, KBS, MBC, SBS, YTN)중 3개 이상의 사이트에서 검색어와 관련된 기사가 존재할 때 뉴스로 제공합니다.</br></br></p>
                  </div>
                  <div class="private_policy">
                    <div class="lh6 bs4"><h3>개인정보처리방침</h3></br></div>
                      <p class="lh6 bs4"><strong>1. 개인정보의 처리 목적</strong></br></br> CatchPick <CatchPick>(‘CatchPick’이하 ‘CatchPick’) 은(는) 다음의 목적을 위하여 개인정보를 처리하고 있으며, 다음의 목적 이외의 용도로는 이용하지 않습니다.</br> - 고객 가입의사 확인, 고객에 대한 서비스 제공에 따른 본인 식별.인증, 회원자격 유지.관리, 물품 또는 서비스 공급에 따른 금액 결제, 물품 또는 서비스의 공급.배송 등</br></br></p>
                      <p class="lh6 bs4"><strong>2. 개인정보의 처리 및 보유 기간</strong></br></br>① CatchPick<CatchPick>(‘CatchPick’이하 ‘CatchPick’) 은(는) 정보주체로부터 개인정보를 수집할 때 동의 받은 개인정보 보유․이용기간 또는 법령에 따른 개인정보 보유․이용기간 내에서 개인정보를 처리․보유합니다.</br></br>② 구체적인 개인정보 처리 및 보유 기간은 다음과 같습니다.</br>☞ 아래 예시를 참고하여 개인정보 처리업무와  개인정보 처리업무에 대한 보유기간 및 관련 법령, 근거 등을 기재합니다. </br>(예시)</br>- 고객 가입 및 관리 : 서비스 이용계약 또는 회원가입 해지시까지, 다만 채권․채무관계 잔존시에는 해당 채권․채무관계 정산시까지</br>- 전자상거래에서의 계약․청약철회, 대금결제, 재화 등 공급기록 : 5년 </br></br></p>
                      <div class="lh6 bs4"><strong>3. 정보주체와 법정대리인의 권리·의무 및 그 행사방법 이용자는 개인정보주체로써 다음과 같은 권리를 행사할 수 있습니다.</strong></div></br><p class="ls2">① 정보주체는 CatchPick(‘CatchPick’이하 ‘CatchPick) 에 대해 언제든지 다음 각 호의 개인정보 보호 관련 권리를 행사할 수 있습니다.</br></br>1. 개인정보 열람요구</br> 2. 오류 등이 있을 경우 정정 요구</br> 3. 삭제요구</br> 4. 처리정지 요구</br></br></p>
                      <div class="lh6 bs4"><strong>4. 처리하는 개인정보의 항목 작성 </strong></br></br> ① <em class="emphasis"><CatchPick>('CatchPick'이하  'CatchPick')</em>은(는) 다음의 개인정보 항목을 처리하고 있습니다.</div><p class='ls2'>1. <이메일발송></br>- 필수항목 : 이메일</br></br></p>
                      <div class="lh6 bs4"><strong>5. 개인정보의 파기<em class="emphasis"><CatchPick>('CatchPick')</em>은(는) 원칙적으로 개인정보 처리목적이 달성된 경우에는 지체없이 해당 개인정보를 파기합니다. 파기의 절차, 기한 및 방법은 다음과 같습니다.</strong></div></br><p class='ls2'>-파기절차</br>이용자가 입력한 정보는 목적 달성 후 별도의 DB에 옮겨져(종이의 경우 별도의 서류) 내부 방침 및 기타 관련 법령에 따라 일정기간 저장된 후 혹은 즉시 파기됩니다. 이 때, DB로 옮겨진 개인정보는 법률에 의한 경우가 아니고서는 다른 목적으로 이용되지 않습니다.</br><br>-파기기한</br>이용자의 개인정보는 개인정보의 보유기간이 경과된 경우에는 보유기간의 종료일로부터 5일 이내에, 개인정보의 처리 목적 달성, 해당 서비스의 폐지, 사업의 종료 등 그 개인정보가 불필요하게 되었을 때에는 개인정보의 처리가 불필요한 것으로 인정되는 날로부터 5일 이내에 그 개인정보를 파기합니다.</br></br></p>
                      <div class="lh6 bs4"><strong>6. 개인정보 자동 수집 장치의 설치•운영 및 거부에 관한 사항</strong></div></br><p class="ls2">CatchPick 은 정보주체의 이용정보를 저장하고 수시로 불러오는 ‘쿠키’를 사용하지 않습니다.</br></br></p>
                      <div class="lh6 bs4"><strong>7. 개인정보 보호책임자 작성 </strong></div></br> ①  CatchPick(‘CatchPick’이하 ‘CatchPick') 은(는) 개인정보 처리에 관한 업무를 총괄해서 책임지고, 개인정보 처리와 관련한 정보주체의 불만처리 및 피해구제 등을 위하여 아래와 같이 개인정보 보호책임자를 지정하고 있습니다.<p class='ls2'><br/>▶ 개인정보 보호책임자 <br/>성명 :김현곤<br/>직책 :개발자<br/>직급 : 개발자<br/>연락처 : 010-5412-9697<br/> E-mail : simonkim@kookmin.ac.kr <br/> <br/><br/>② 정보주체께서는 CatchPick(‘CatchPick’이하 ‘CatchPick) 의 서비스(또는 사업)을 이용하시면서 발생한 모든 개인정보 보호 관련 문의, 불만처리, 피해구제 등에 관한 사항을 개인정보 보호책임자 및 담당부서로 문의하실 수 있습니다. CatchPick(‘CatchPick’이하 ‘CatchPick) 은(는) 정보주체의 문의에 대해 지체 없이 답변 및 처리해드릴 것입니다.</br></br></p>
                      <div class="lh6 bs4"><strong>8. 개인정보 처리방침 변경 </strong></div></br><p>①이 개인정보처리방침은 시행일로부터 적용되며, 법령 및 방침에 따른 변경내용의 추가, 삭제 및 정정이 있는 경우에는 변경사항의 시행 7일 전부터 공지사항을 통하여 고지할 것입니다.</br></br></p>
                      <div class="lh6 bs4"><strong>9. 개인정보의 안전성 확보 조치 <em class="emphasis"><CatchPick>('CatchPick')</em>은(는) 개인정보보호법 제29조에 따라 다음과 같이 안전성 확보에 필요한 기술적/관리적 및 물리적 조치를 하고 있습니다.</strong></div></br><div class='ls2'>1. 정기적인 자체 감사 실시</br> 개인정보 취급 관련 안정성 확보를 위해 정기적(분기 1회)으로 자체 감사를 실시하고 있습니다.</br></br>2. 개인정보 취급 직원의 최소화 및 교육</br> 개인정보를 취급하는 직원을 지정하고 담당자에 한정시켜 최소화 하여 개인정보를 관리하는 대책을 시행하고 있습니다.</br></br>3. 내부관리계획의 수립 및 시행</br> 개인정보의 안전한 처리를 위하여 내부관리계획을 수립하고 시행하고 있습니다.</br></br>4. 해킹 등에 대비한 기술적 대책</br> <<em class="emphasis">CatchPick</em>>('<em class="emphasis">CatchPick</em>')은 해킹이나 컴퓨터 바이러스 등에 의한 개인정보 유출 및 훼손을 막기 위하여 보안프로그램을 설치하고 주기적인 갱신·점검을 하며 외부로부터 접근이 통제된 구역에 시스템을 설치하고 기술적/물리적으로 감시 및 차단하고 있습니다.</br></br>5. 접속기록의 보관 및 위변조 방지</br> 개인정보처리시스템에 접속한 기록을 최소 6개월 이상 보관, 관리하고 있으며, 접속 기록이 위변조 및 도난, 분실되지 않도록 보안기능 사용하고 있습니다.</br></br>6. 개인정보에 대한 접근 제한</br> 개인정보를 처리하는 데이터베이스시스템에 대한 접근권한의 부여,변경,말소를 통하여 개인정보에 대한 접근통제를 위하여 필요한 조치를 하고 있으며 침입차단시스템을 이용하여 외부로부터의 무단 접근을 통제하고 있습니다.</br></br></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js'%}"></script>

</body>

</html>

catchpick/newsCatch/templates/newsCatch/sub_emailError.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <title>오류발생!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="{% static 'fav.ico'%}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'fonts/fontawesome-free/css/fontawesome.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/iconic/css/material-design-iconic-font.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">

    <link href="{% static 'css/overlap.css'%}" rel='stylesheet'/>

    <script>
    function goBack() {
        window.history.back();
    }
    </script>

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-30 p-b-20">
			<span class="login100-form-title p-b-50">
				Error
			</span>
            <span class="login100-form-avatar">
				<img src="{% static 'img/kmulogo.jpg'%}" alt="AVATAR">
			</span>

            <p style="text-align: center; font-size: large"><strong><br>중복된 이메일이거나 올바른 이메일이 아닙니다.</strong><br><br><br> </p>

            <div class="container-login100-form-btn">
                <a class="login100-form-btn unshadow" href="{% url 'newsCatch:subscription' %}">돌아가기</a>
            </div>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'vendor/jquery/jquery.js'%}"></script>
<script src="{% static 'vendor/animsition/js/animsition.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'vendor/select2/select2.min.js'%}"></script>
<script src="{% static 'vendor/daterangepicker/moment.min.js'%}"></script>
<script src="{% static 'vendor/daterangepicker/daterangepicker.js'%}"></script>
<script src="{% static 'vendor/countdowntime/countdowntime.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>

</body>
</html>

catchpick/newsCatch/templates/newsCatch/unsub_emailError.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <title>오류발생!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="{% static 'fav.ico'%}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'fonts/fontawesome-free/css/fontawesome.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/iconic/css/material-design-iconic-font.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css'%}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">

    <link href="{% static 'css/overlap.css'%}" rel='stylesheet'/>

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-30 p-b-20">
			<span class="login100-form-title p-b-50">
				Error
			</span>
            <span class="login100-form-avatar">
				<img src="{% static 'img/kmulogo.jpg'%}" alt="AVATAR">
			</span>

            <p style="text-align: center; font-size: large"><strong><br>구독하지 않은 이메일이거나 올바른 이메일이 아닙니다.</strong><br><br><br> </p>

            <div class="container-login100-form-btn">
                <a class="login100-form-btn unsubs unshadow" href="{% url 'newsCatch:unsubscription' %}">돌아가기</a>
            </div>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'vendor/jquery/jquery.js'%}"></script>
<script src="{% static 'vendor/animsition/js/animsition.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'vendor/select2/select2.min.js'%}"></script>
<script src="{% static 'vendor/daterangepicker/moment.min.js'%}"></script>
<script src="{% static 'vendor/daterangepicker/daterangepicker.js'%}"></script>
<script src="{% static 'vendor/countdowntime/countdowntime.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>

</body>
</html>